services:
  - type: web
    name: spaced-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn my_agent.agent:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: https://getspaced.app,http://localhost:3000,http://localhost:8080 