// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7mx3zZYsXe46aXIJAhGGBYCLOGcYbwk',
    appId: '1:605253712819:web:30af37d6ca11a08916e9c6',
    messagingSenderId: '605253712819',
    projectId: 'spaced-b571d',
    authDomain: 'spaced-b571d.firebaseapp.com',
    storageBucket: 'spaced-b571d.firebasestorage.app',
    measurementId: 'G-BQP86B87HD',
    iosClientId:
        '605253712819-fnst7pbbgu88p8m7bbk8oq5hohibsamr.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-LWHUGOWUtkyFrphc6310q2oj8hPxVo',
    appId: '1:605253712819:android:7258e8f36170d1ea16e9c6',
    messagingSenderId: '605253712819',
    projectId: 'spaced-b571d',
    storageBucket: 'spaced-b571d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApr8hCqHnc6o3waHWXNKn9qxiDneXJxrM',
    appId: '1:605253712819:ios:53f6d0d219f56dec16e9c6',
    messagingSenderId: '605253712819',
    projectId: 'spaced-b571d',
    storageBucket: 'spaced-b571d.firebasestorage.app',
    iosClientId:
        '605253712819-fnst7pbbgu88p8m7bbk8oq5hohibsamr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lrScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApr8hCqHnc6o3waHWXNKn9qxiDneXJxrM',
    appId: '1:605253712819:ios:53f6d0d219f56dec16e9c6',
    messagingSenderId: '605253712819',
    projectId: 'spaced-b571d',
    storageBucket: 'spaced-b571d.firebasestorage.app',
    iosClientId:
        '605253712819-fnst7pbbgu88p8m7bbk8oq5hohibsamr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lrScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg7mx3zZYsXe46aXIJAhGGBYCLOGcYbwk',
    appId: '1:605253712819:web:7b0d23789b3a671916e9c6',
    messagingSenderId: '605253712819',
    projectId: 'spaced-b571d',
    authDomain: 'spaced-b571d.firebaseapp.com',
    storageBucket: 'spaced-b571d.firebasestorage.app',
    measurementId: 'G-QVYXJX4Q3Y',
  );
}
