name: Backend CI

on:
  push:
    branches:
      - main
      - 'f/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run Ruff linter
        run: ruff check backend/

      - name: Run Ruff formatter check
        run: ruff format backend/ --check 