# Dual-domain deployment workflow for getspaced.app and app.getspaced.app
name: Deploy to Dual Domains

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job - builds Flutter app once for both domains
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          
      - name: Report Flutter & Dart versions
        run: |
          flutter --version
          dart --version
          
      - name: Get dependencies
        run: |
          cd flutter_app
          flutter pub get
        
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Build web with optimizations
        run: |
          cd flutter_app
          # Build with basic performance optimizations
          flutter build web --release --tree-shake-icons
          
      - name: Verify build output
        run: |
          echo "Checking build directory contents:"
          ls -la flutter_app/build/web/
          echo "Checking main.dart.js exists:"
          ls -la flutter_app/build/web/main.dart.js || echo "main.dart.js is missing!"
        
      - name: Prepare web files
        run: |
          # Create .nojekyll file to bypass Jekyll processing
          touch flutter_app/build/web/.nojekyll
          
          # Simple 404.html for SPA routing
          cat > flutter_app/build/web/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Spaced</title>
            <script>
              var l = window.location;
              l.replace(l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') + l.pathname.split('/').slice(0, 1).join('/') + '/' + l.pathname.slice(1).split('/').slice(0).join('/') + (l.search || '') + l.hash);
            </script>
          </head>
          <body><p>Redirecting...</p></body>
          </html>
          EOL

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: flutter_app/build/web/
          retention-days: 1

  # Deploy to main domain (getspaced.app)
  deploy-main:
    needs: build
    environment:
      name: github-pages
      url: https://getspaced.app
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-build
          path: ./web-build
          
      - name: Create CNAME for main domain
        run: echo "getspaced.app" > ./web-build/CNAME
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web-build'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Deploy to app subdomain (app.getspaced.app) 
  deploy-app:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download build artifact  
        uses: actions/download-artifact@v4
        with:
          name: flutter-build
          path: ./web-build
          
      - name: Deploy to app subdomain
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
          cname: app.getspaced.app
          force_orphan: true 